title: 晴十二郎
subtitle: 一九八三年小巷
description: 十二月晴朗

author: 晴十二郎
email: showarm@163.com
avatar: assets/images/avatar.jpg

baseurl: ""
url: "http://showarm.github.io"

# Social settings
# facebook_url: https://www.facebook.com/chris.bobbe
# linkedin_url: https://www.linkedin.com/in/chrisbobbe1995/
github_url: https://github.com/showarm
twitter_url: https://twitter.com/youngpeanut

# SEO settiongs
google_analytics: UA-112211352-1

# Build settings
remote_theme: chrisbobbe/jekyll-theme-prologue
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Necessary for Prologue theme:
collections: [sections]