name:               "YoungPeanut"
description:        "love this world"

url:                "http://youngpeanut.github.io"
author:             "YoungPeanut"
email:              "shibuxing.com"
avatar_url:      "http://hoop8.com/1610A/EyQ8Z4yj.png"

weibo:            "YoungPeanut"
twitter:            "info_ipeanut"
github:             "YoungPeanut"

disqus_shortname:   "YoungPeanut"

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           8
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate



theme: jekyll-theme-dinky